### ISSUE TITLE
Python script fails to authenticate 

### ISSUE THREAD

**Issue by etwatson** [domrout/python-twitter-wrapper#6]
Hi,
I wrote a script that polls a thermal sensor and tweets the result that works fabulously if you run it from the directory that the script is in. Yet, when I run it from another location or with a cron job, I get the following error:

The good (stores data to SQL and tweets if above or below a threshold):
```
root@raspberrypi:/usr/lib/cgi-bin# ./tweet.py 
YES
25.187
temperature=25.187
```

The bad:
```
root@raspberrypi:~# /usr/lib/cgi-bin/tweet.py 
Traceback (most recent call last):
  File "/usr/lib/cgi-bin/tweet.py", line 3, in <module>
    api = twitterwrapper.Api()
  File "/src/twitterwrapper/twitterwrapper/_api.py", line 221, in __init__
    connection = connection if connection else config_connection()
  File "/src/twitterwrapper/twitterwrapper/access_tokens.py", line 121, in config_connection
    store.load()
  File "/src/twitterwrapper/twitterwrapper/access_tokens.py", line 50, in load
    raise IOError("Access token file %s couldn't be opened. Try running authenticate_twitter_cherrypy ?" % self.filename)
IOError: Access token file access_tokens.yaml couldn't be opened. Try running authenticate_twitter_cherrypy ?
```

**Comment by domrout** [comment]
Hi! did you run the script authenticate_twitter_cherrypy as described on the README to create a Twitter access token file? That file should be placed in the working directory for your python script. 

You will also need a consumer key, which you can obtain by registering an application with Twitter.

If you prefer to contact me by email for help with the library, please feel free. My contact details are available on http://domrout.co.uk/

**Comment by etwatson** [comment]
I originally used your authenticate_twitter.py script, which successfully created access_tokens.yaml and, as I mentioned, my script is able to post on twitter when run from that subdirectory. The script includes: 
```
import twitterwrapper
api = twitterwrapper.Api()
new_status = api.statuses.update("A new update")
```
As I mentioned above, the script doesn't work with crontab or when called from another location, and it asks for me to 'try authenticate_twitter_cherrypy'.
When I try ```authenticate_twitter_cherrypy`` I get this error:
```
root@raspberrypi:/usr/lib/cgi-bin# authenticate_twitter_cherrypy
Traceback (most recent call last):
  File "/usr/local/bin/authenticate_twitter_cherrypy", line 4, in <module>
    from pkg_resources import require; require('TwitterWrapper==0.1')
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2707, in <module>
    working_set.require(__requires__)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 686, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 584, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: oauth2
```

**Comment by etwatson** [comment]
when I call, ```athenticate_twitter``` or ```authenticate_twitter_cherrypy``` I get the above error. However, the athenticate_twitter script works if I copy the script from ```/src/twitterwrapper/scripts/``` to my working directory, which has consumer.yaml. When I copy authenticate_twitter_cherrypy script to my working directory I get the error:

```
root@raspberrypi:/usr/lib/cgi-bin# ./authenticate_twitter_cherrypy 
[22/Sep/2015:23:37:50] ENGINE Bus STARTING
CherryPy Checker:
The Application mounted at '' has an empty config.

[22/Sep/2015:23:37:50] ENGINE Started monitor thread 'Autoreloader'.
[22/Sep/2015:23:37:50] ENGINE Started monitor thread '_TimeoutMonitor'.
[22/Sep/2015:23:37:51] ENGINE Serving on http://127.0.0.1:8080
[22/Sep/2015:23:37:51] ENGINE Bus STARTED
```
...and it hangs there.

**Comment by domrout** [comment]
If you have already managed to use the script version of the process (authenticate_twitter) and created an access token, you don't need the cherrypy version - the cherrypy version is a nicer interface to it. It waits for you to connect on http://127.0.0.1:8080 - and actually tries to launch your browser to do so. Unfortunately launching a browser for the user does not always give predictable results. I will improve the feedback for that soon.

As to your issue with running under CronTab or from a different location - this is because both activities change your working directory, and the simplest way of using the library assumes that the key file is in the root of your working directory. You can supply another location (perhaps an absolute location?) for the file as follows:

connection = twitterwrapper.config_connection("some_user_name", "/a/folder/access_tokens.yaml")
api = twitterwrapper.Api(connection)

Hope this helps!

Dom

**Comment by etwatson** [comment]
Wow, sorry for the delay. That did indeed help. Thank you!
